### ISSUE TITLE
panic: runtime error: slice bounds out of range [1:0]

### ISSUE THREAD

**Issue by Twistedmock** [Brum3ns/firefly#8]
I tried to run this command and got the error below

firefly  -u "http://testphp.vulnweb.com/redir.php?r=https://x.com"

panic: runtime error: slice bounds out of range [1:0]

goroutine 40 [running]:
github.com/Brum3ns/firefly/pkg/request.worker.request({_, _, _, _}, {0x1, 0x0, {0xc0000cc020, 0x20}, {0x7ae58a, 0x6}, ...})
	/home/g/go/pkg/mod/github.com/!brum3ns/firefly@v0.0.0-20230917212651-1b19ed6e4769/pkg/request/request.go:145 +0x9a7
github.com/Brum3ns/firefly/pkg/request.worker.spawnRequestWorker.func1()
	/home/g/go/pkg/mod/github.com/!brum3ns/firefly@v0.0.0-20230917212651-1b19ed6e4769/pkg/request/handler.go:171 +0x11e
created by github.com/Brum3ns/firefly/pkg/request.worker.spawnRequestWorker
	/home/g/go/pkg/mod/github.com/!brum3ns/firefly@v0.0.0-20230917212651-1b19ed6e4769/pkg/request/handler.go:163 +0xcb

**Comment by Brum3ns** [comment]
Hey Twistedmock,

I will fix quickly, thanks for reaching out!

Regards,
Brumens

**Comment by Brum3ns** [comment]
The error should now be fixed, thanks for letting me know!

Does the fix for the issue work?

---

*In case you experience a lot of output to the CLI screen when no filter is in use, it's an "issue" I'm aware of and that will soon be fixed in a few days*

Thanks again!

**Comment by Twistedmock** [comment]
Hi, Thanks for fixing it in such a short time. 

In most of the targets, firefly is working just fine. 

But still I got some error with some targets. I used -scheme argument as well to match the protocol, still getting error. Provably problem with the  tls connection .

![2023-09-26_18-10](https://github.com/Brum3ns/firefly/assets/88490703/82d4fd4c-d19f-4f2b-b6fb-7fab743b3eae)


Anyway, it is working fine. Thanks again.

**Comment by brumensywh** [comment]
Thanks for letting me know
I will include these fixes and some that I'm aware of in just a few days, I will net you know once It's fixed!

**Comment by Brum3ns** [comment]
Thanks for letting me know
I will include these fixes and some that I'm aware of in just a few days, I will net you know once It's fixed!

**Comment by Brum3ns** [comment]
This issues are now fixed

Thanks for being a part of improving Firefly!
